apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: interstellar-frontend-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: interstellar-frontend-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90