apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: interstellar-logs-api-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: interstellar-logs-api-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 90