name: CI
on:
  push:
    branches: [ prod ]
#   pull_request:
#     branches: [ prod ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Publish to Docker Registry (Service - frontend)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.DOCKER_USERNAME }}/interstellar-frontend
        tags: "latest"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: services/frontend
    - name: Publish to Docker Registry (Service - profile-api)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.DOCKER_USERNAME }}/interstellar-profile-api
        tags: "latest"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: services/profile-api
    - name: Publish to Docker Registry (Service - logs-api)
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ secrets.DOCKER_USERNAME }}/interstellar-logs-api
        tags: "latest"
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        workdir: services/logs-api
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Set up kubectl
      uses: matootie/dokube@v1.3.1
      with:
        personalAccessToken: ${{ secrets.DIGITALOCEAN_TOKEN }}
        clusterName: ${{ secrets.KUBE_CLUSTER_NAME }}
        expirationTime: "300"
        version: "1.17.4"
    - uses: actions/checkout@v2
    - name: Apply configuration files 
      run: |
        cd kubernetes
        kubectl apply -f ingress.yaml
        kubectl apply -f frontend_deployment.yaml
        kubectl apply -f frontend_service.yaml
        kubectl apply -f frontend_autoscaler.yaml
        kubectl rollout restart deployment interstellar-frontend-deployment
        kubectl apply -f profile_api_deployment.yaml
        kubectl apply -f profile_api_service.yaml
        kubectl apply -f profile_api_autoscaler.yaml
        kubectl rollout restart deployment interstellar-profile-api-deployment
        kubectl apply -f ingress.yaml
        kubectl apply -f frontend_deployment.yaml
        kubectl apply -f frontend_service.yaml
        kubectl apply -f frontend_autoscaler.yaml
        kubectl rollout restart deployment interstellar-frontend-deployment
  notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Email Notification
        uses: dawidd6/action-send-mail@v2.2.0
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "Job Status: ${{job.status}} | Portfolio - Arjun S"
          body: |
            Job Status: ${{job.status}}
            Run Status: https://github.com/ArjunInventor/portfolio/actions/runs/${{github.run_id}}
            Initiated by: ${{github.actor}}
          to: arjun.santhoshkumar@gmail.com
          from: ${{ secrets.MAIL_USERNAME }}
        
